// --- DATABASE DELLE DOMANDE ---
const mazzo = [

    // --- STANDARD ---
    { tipo: 'standard', cat: 'Sincronia', domande: ['Gusto di gelato preferito', 'Un soprannome ridicolo', 'App più usata sul telefono'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Pizza preferita', 'Una fobia comune', 'Materia scolastica più odiata'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Città dei sogni', 'Giorno della settimana preferito', 'Un animale domestico'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Bevanda da ordinare al bar', 'Colore dell’auto ideale', 'Genere cinematografico preferito'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Cosa non manca mai in frigo', 'Un superpotere desiderato', 'Il primo concerto visto'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Gusto di patatine', 'Un cattivo dei film', 'Sport più noioso da vedere'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Marca di scarpe preferita', 'Cosa si mangia a colazione', 'Un oggetto inutile in casa'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Cibo preferito dopo l’allenamento', 'Un programma TV che tutti amano tranne te', 'Giorno ideale per il relax'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La peggior figura di merda mai fatta', 'Un concerto a cui vorresti andare', 'Cosa cerchi su Google più spesso'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il tuo primo indirizzo email', 'Un gioco dell’infanzia', 'Gusto di tè preferito'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un posto dove non andresti mai in vacanza', 'Il tuo secondo nome ideale', 'La cosa che ti rende più ansioso'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un personaggio storico preferito', 'Cosa compri sempre in autogrill', 'Il momento più bello della giornata'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un film d’animazione sottovalutato', 'La tua "confort zone" a tavola', 'Quante ore dormi di solito'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un talento che vorresti rubare', 'Il tuo profumo preferito', 'Cosa fai se non riesci a dormire'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua serie TV preferita di sempre', 'Un acquisto impulsivo recente', 'La tua opinione sui cornetti salati'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un viaggio che ha cambiato tutto', 'Cosa metteresti sulla pizza per sfida', 'Il tuo segno zodiacale'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un posto della casa dove ti senti al sicuro', 'La tua marca di bibite preferita', 'Cosa faresti con un milione di euro'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il tuo primo cellulare', 'Un’abitudine che vuoi eliminare', 'La tua bevanda alcolica preferita'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Una parola che trovi buffa', 'Il tuo sportivo preferito', 'Cosa cucini se hai ospiti all’ultimo'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il tuo mese preferito', 'Una canzone che ti ricorda l’estate', 'Cosa c’è nel tuo cassetto dei sogni'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un film che non hai mai finito', 'La tua applicazione più inutile', 'Cosa fai appena torni da lavoro'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il tuo colore di capelli preferito', 'Un accessorio che indossi sempre', 'La tua colazione dei campioni'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un posto che ti ricorda l’infanzia', 'Il tuo frutto preferito', 'La tua paura più irrazionale'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un’attività che ti rilassa', 'Il tuo stile di arredamento', 'Cosa pensi delle scarpe con le dita'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua festa preferita', 'Un libro che consiglieresti a tutti', 'Il tuo videogioco del cuore'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua prima parola da bambino', 'Un oggetto che hai perso e rimpiangi', 'La tua stagione ideale per viaggiare'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un sito web che visiti ogni giorno', 'La tua opinione sul campeggio', 'Cosa non sopporti al cinema'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il tuo animale selvaggio preferito', 'Un pezzo d’abbigliamento che odi', 'La tua ora preferita del giorno'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Cosa fai per festeggiare', 'Un dolce tipico che ami', 'Il tuo attore preferito'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua bevanda preferita al cinema', 'Un’esperienza che non rifaresti mai', 'Il tuo primo lavoro'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Cosa pensi della domotica', 'Il tuo genere musicale preferito', 'Una fiera a cui vorresti andare'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua merenda preferita', 'Un posto dove vorresti vivere da vecchio', 'Cosa fai quando piove'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un film che conosci a memoria', 'La tua marca di pasta preferita', 'Un regalo che vorresti ricevere'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua città d’arte preferita', 'Un’app di messaggistica che odi', 'Cosa pensi degli alieni'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il tuo cocktail da aperitivo', 'Un evento storico a cui vorresti assistere', 'Cosa compri sempre online'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua materia scolastica preferita', 'Un posto della tua città che odi', 'Cosa fai nel tempo libero'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il tuo piatto di pasta preferito', 'Un superpotere inutile', 'Cosa pensi dei social media'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua isola preferita', 'Un gioco di carte', 'Cosa guardi per primo in una casa'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua bevanda calda preferita', 'Un’abitudine mattutina', 'Cosa pensi del futuro'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il tuo fiore preferito', 'Un posto segreto che conosci', 'Cosa non compri mai'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua scarpa ideale', 'Un programma radiofonico', 'Cosa pensi della moda'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il tuo gioco da tavolo preferito', 'Un ricordo d’estate', 'Cosa fai la domenica mattina'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua spezia preferita', 'Un oggetto di design', 'Cosa pensi dei tatuaggi'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il tuo castello preferito', 'Un’app per le foto', 'Cosa fai se vinci alla lotteria'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua montagna preferita', 'Un tipo di formaggio', 'Cosa pensi dell’intelligenza artificiale'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il tuo sport preferito da praticare', 'Un ricordo di scuola', 'Cosa fai per distrarti'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['La tua lingua straniera preferita', 'Un oggetto sulla tua scrivania', 'Cosa pensi dei viaggi nello spazio'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Gusto di granita', 'Un numero da 1 a 10', 'Il tasto più usato sulla tastiera'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un ingrediente del panino ideale', 'Il colore della tua maglietta preferita', 'Un oggetto che hai in tasca'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il primo animale che ti viene in mente', 'Un nome di battesimo maschile', 'La tua marca di orologi'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Cosa metti nel caffè', 'Un cartone animato degli anni 90', 'Il tuo modo di cucinare le uova'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un mese autunnale', 'La tua marca di zaini', 'Un oggetto che tieni in auto'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Una parola che inizia con la Z', 'Il tuo primo pensiero del lunedì', 'Un tipo di pasta corta'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Il tuo condimento per l’insalata', 'Un pianeta del sistema solare', 'La tua marca di acqua preferita'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Cosa compri in edicola', 'Un attore di film d’azione', 'Il tuo secondo colore preferito'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di frutta esotica', 'La tua marca di computer', 'Un mestiere che si fa all’aperto'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Una capitale europea', 'Il tuo dolce tipico natalizio', 'Cosa usi per profumare la casa'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un fiore primaverile', 'La tua catena di fast food', 'Un oggetto che porti in spiaggia'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un pezzo degli scacchi', 'Il tuo tipo di cioccolato preferito', 'Una parte del corpo che ti prude spesso'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un condimento per i popcorn', 'Il tuo servizio di streaming preferito', 'Un elettrodomestico rumoroso'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un gusto di chewing-gum', 'La tua marca di jeans', 'Un insetto fastidioso'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un materiale da costruzione', 'Il tuo gioco di carte preferito', 'Cosa mangi a merenda'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di danza', 'La tua marca di occhiali', 'Un oggetto che hai sul comodino'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un colore primario', 'Il tuo ortaggio preferito', 'Cosa bevi durante i pasti'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un mobile della camera da letto', 'La tua marca di intimo', 'Un suono rilassante'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di borsa', 'La tua lingua straniera preferita', 'Cosa fai se hai un minuto libero'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un agrume', 'Il tuo browser internet', 'Un accessorio per i capelli'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di formaggio spalmabile', 'La tua marca di attrezzi sportivi', 'Un rumore che non sopporti'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un uccello notturno', 'Il tuo colore di penna preferito', 'Cosa tieni nel portafoglio'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di biscotto da inzuppo', 'La tua marca di prodotti per capelli', 'Un traguardo della vita'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un albero da frutto', 'Il tuo social media preferito', 'Un oggetto che tieni in bagno'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di carne', 'La tua marca di gomme da masticare', 'Cosa metti nello zaino'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un genere letterario', 'Il tuo motore di ricerca', 'Un accessorio da cucina'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di calzatura estiva', 'La tua marca di birra', 'Un oggetto che hai in borsa'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un personaggio storico', 'Il tuo condimento per la pasta al forno', 'Un fastidio fisico comune'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di latte', 'La tua marca di yogurt', 'Un oggetto che hai sulla scrivania'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un mare del mondo', 'Il tuo cantante solista preferito', 'Un oggetto che tieni in garage'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di infuso', 'La tua marca di sapone', 'Un dettaglio del viso'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un attrezzo da giardinaggio', 'Il tuo sito di e-commerce preferito', 'Un modo di salutare'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di fungo', 'La tua marca di tè', 'Un oggetto che tieni sotto il letto'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un crostaceo', 'Il tuo programma radiofonico', 'Un indumento invernale'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di salsa', 'La tua marca di cereali', 'Un oggetto che tieni in corridoio'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un metallo prezioso', 'Il tuo genere di danza', 'Un oggetto che hai nel cruscotto'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di pizza bianca', 'La tua marca di detersivo', 'Un particolare del panorama'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un dolce al cucchiaio', 'Il tuo servizio mail', 'Un oggetto che tieni in soffitta'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di legume', 'La tua marca di snack salati', 'Un accessorio per lo smartphone'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un rettile', 'Il tuo metodo di pagamento preferito', 'Un oggetto che hai in cantina'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di riso', 'La tua marca di cancelleria', 'Un dettaglio di un’auto'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un pesce di mare', 'Il tuo orario preferito per cenare', 'Un oggetto che hai sul balcone'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di vino bianco', 'La tua marca di cioccolato', 'Un gesto scaramantico'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un rapace', 'Il tuo tipo di caffè preferito', 'Un oggetto che hai nell’ingresso'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di pane regionale', 'La tua marca di succhi di frutta', 'Un’abitudine fastidiosa altrui'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un eroe dei miti greci', 'Il tuo colore di ombrello', 'Un oggetto che hai nel ripostiglio'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di pasta lunga', 'La tua marca di conserve', 'Un dettaglio di una scarpa'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un mammifero marino', 'Il tuo canale TV preferito', 'Un oggetto che hai nella cassetta dei medicinali'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di formaggio stagionato', 'La tua marca di olio d’oliva', 'Un modo di dire dialettale'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un vulcano famoso', 'Il tuo colore di lenzuola', 'Un oggetto che hai nella borsa della palestra'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un felino selvaggio', 'La tua marca di biscotti preferita', 'Un accessorio da campeggio'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di mela', 'Il tuo font preferito', 'Un oggetto che hai nella cassetta degli attrezzi'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un’isola italiana', 'La tua marca di profumo', 'Un dettaglio del tuo ufficio/camera'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di insalata', 'La tua marca di cuffie', 'Un oggetto che hai in cucina'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un cane di taglia piccola', 'Il tuo tipo di amaro preferito', 'Un accessorio da scrivania'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un attrezzo da palestra', 'La tua marca di bibite gassate', 'Un oggetto che hai nel portone'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di uva', 'Il tuo personaggio dei Simpson preferito', 'Un dettaglio della tua bici'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un mobile del salotto', 'La tua marca di gelati confezionati', 'Un oggetto che hai in valigia'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di dado da gioco', 'Il tuo modello di scarpe Nike preferito', 'Un dettaglio del bagno'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un modo di cuocere la carne', 'La tua marca di dentifricio', 'Un oggetto che hai sotto il sedile'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di zucchero', 'Il tuo gusto di marmellata', 'Un dettaglio della tua porta di casa'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un componente del PC', 'La tua marca di pasta preferita', 'Un oggetto che hai nel cruscotto'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di salsa per patatine', 'Il tuo modello di iPhone preferito', 'Un dettaglio del tuo portafoglio'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un animale della fattoria', 'La tua marca di pneumatici', 'Un oggetto che hai in tasca della giacca'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di pepe', 'Il tuo colore di portafoglio', 'Un dettaglio della tua cucina'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un attrezzo da idraulico', 'La tua marca di tonno preferita', 'Un oggetto che hai nel cassetto delle posate'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di farina', 'Il tuo attore comico preferito', 'Un dettaglio del tuo orologio'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un animale della giungla', 'La tua marca di caffè preferita', 'Un oggetto che hai sul frigorifero'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di sale', 'Il tuo genere di videogiochi preferito', 'Un dettaglio del tuo letto'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un utensile per scrivere', 'La tua marca di latte preferita', 'Un oggetto che hai nel sottoscala'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un animale della savana', 'Il tuo gusto di pizza preferito', 'Un dettaglio della tua finestra'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di aceto', 'La tua marca di patatine preferita', 'Un oggetto che hai nel cassetto dei calzini'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un attrezzo da falegname', 'Il tuo colore di smartphone preferito', 'Un dettaglio del tuo zaino'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un animale domestico insolito', 'La tua marca di burro preferita', 'Un oggetto che hai nel congelatore'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di mostarda', 'Il tuo canale YouTube preferito', 'Un dettaglio della tua lampada'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un attrezzo da elettricista', 'La tua marca di riso preferita', 'Un oggetto che hai nel mobile bar'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un animale del deserto', 'Il tuo gusto di granita preferito', 'Un dettaglio della tua sedia'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di olio per cucinare', 'La tua marca di tè preferita', 'Un oggetto che hai nello specchio'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un attrezzo da muratore', 'Il tuo modello di auto preferito', 'Un dettaglio della tua TV'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un animale del bosco', 'La tua marca di maionese preferita', 'Un oggetto che hai sul davanzale'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di spezia piccante', 'Il tuo gusto di gelato preferito', 'Un dettaglio del tuo divano'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un utensile per disegnare', 'La tua marca di cereali preferita', 'Un oggetto che hai nel forno'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un animale dell’oceano', 'Il tuo gusto di caramelle preferito', 'Un dettaglio della tua scrivania'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di salsa barbecue', 'La tua marca di succhi preferita', 'Un oggetto che hai nel microonde'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un attrezzo da meccanico', 'Il tuo modello di computer preferito', 'Un dettaglio della tua libreria'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un animale della montagna', 'La tua marca di acqua preferita', 'Un oggetto che hai nel lavandino'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di erba aromatica', 'Il tuo gusto di yogurt preferito', 'Un dettaglio della tua scarpiera'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un utensile per dipingere', 'La tua marca di detersivo preferita', 'Un oggetto che hai nella doccia'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un animale del polo nord', 'Il tuo gusto di tavoletta di cioccolato', 'Un dettaglio del tuo tappeto'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di senape', 'La tua marca di biscotti preferita', 'Un oggetto che hai nella vasca'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un attrezzo da sarto', 'Il tuo modello di tablet preferito', 'Un dettaglio della tua tenda'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un animale della tundra', 'La tua marca di yogurt preferita', 'Un oggetto che hai nel bidet'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di peperoncino', 'Il tuo gusto di sorbetto preferito', 'Un dettaglio della tua porta'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un utensile per scolpire', 'La tua marca di snack preferita', 'Un oggetto che hai nel giardino'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un animale della prateria', 'Il tuo gusto di ghiacciolo preferito', 'Un dettaglio del tuo cancello'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di aceto balsamico', 'La tua marca di cioccolata preferita', 'Un oggetto che hai nel garage'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un attrezzo da calzolaio', 'Il tuo modello di cuffie preferito', 'Un dettaglio della tua siepe'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un animale della steppa', 'Il tuo gusto di milkshake preferito', 'Un oggetto che hai nel vialetto'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un tipo di olio essenziale', 'La tua marca di sapone preferita', 'Un dettaglio del tuo citofono'] },
    { tipo: 'standard', cat: 'Sincronia', domande: ['Un utensile per incidere', 'Il tuo gusto di frappé preferito', 'Un oggetto che hai nel ripostiglio'] },
    
    // --- FLASH ---
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Mare o Montagna?', '2. Rosso di sera...', '3. Apple o Samsung?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pizza o Sushi?', '2. Chi dorme non piglia...', '3. WhatsApp o Telegram?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Dolce o Salato?', '2. Tanto va la gatta al lardo...', '3. Netflix o Disney+?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Caffè o Tè?', '2. Meglio tardi che...', '3. Chiamata o Messaggio?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Cani o Gatti?', '2. L’erba del vicino...', '3. Estate o Inverno?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Doccia o Vasca?', '2. Il mattino ha l’oro...', '3. Instagram o TikTok?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Carne o Pesce?', '2. Chi la fa...', '3. Spotify o Radio?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Birra o Vino?', '2. Ogni lasciata è...', '3. PC o Console?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Rock o Pop?', '2. Una ciliegia tira l’altra...', '3. Amazon o Negozio fisico?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Bianco o Nero?', '2. L’abito non fa...', '3. Sci o Mare?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Mattina o Sera?', '2. Ride bene chi ride...', '3. Hamburger o Hot dog?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Giallo o Blu?', '2. Sbagliando s’impara...', '3. Treno o Aereo?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Scienza o Storia?', '2. Non tutto quello che luccica...', '3. Kindle o Libro?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Yoga o Boxe?', '2. Patti chiari...', '3. Uber o Taxi?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Commedia o Horror?', '2. Volere è...', '3. Coca o Pepsi?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Barba o Pulito?', '2. Occhio non vede...', '3. Mac o Windows?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Foto o Video?', '2. L’unione fa la...', '3. Facebook o YouTube?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Jeans o Felpa?', '2. Chi cerca...', '3. Burger King o McDonald?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pane o Riso?', '2. L’appetito vien...', '3. Gmail o Outlook?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Rosso o Verde?', '2. Morto un papa...', '3. Nike o Adidas?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Sabato o Domenica?', '2. Aiutati che il ciel...', '3. Scarpe o Piedi nudi?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Oro o Argento?', '2. Chi non risica...', '3. Chrome o Safari?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Matita o Penna?', '2. La pazienza è la virtù...', '3. Harry Potter o Star Wars?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Occhiali o Lenti?', '2. Mal comune...', '3. Marvel o DC?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Cappello o Berretto?', '2. Non dire gatto...', '3. Google o Bing?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Sciarpa o Guanti?', '2. Buon sangue non...', '3. PayPal o Satispay?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Biondi o Mori?', '2. Tutto è bene quel che...', '3. PlayStation o Xbox?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Sneakers o Tacchi?', '2. Tra il dire e il fare...', '3. Mare o Piscina?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Crostata o Torta?', '2. Gallina vecchia...', '3. Android o iOS?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Zaino o Borsa?', '2. Il lupo perde il pelo...', '3. Skype o Zoom?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pantaloni o Gonna?', '2. Meglio soli che...', '3. Telegram o Signal?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Camicia o T-shirt?', '2. In alto i...', '3. Spotify o Apple Music?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Occhi chiari o scuri?', '2. Chi va piano...', '3. Twitter o Threads?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Città o Campagna?', '2. Sotto la panca...', '3. SUV o Berlina?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Gelato o Granita?', '2. Acqua passata...', '3. Volo diretto o scalo?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Felpa o Maglione?', '2. A ogni morte di...', '3. Airbnb o Hotel?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pasta corta o lunga?', '2. Chi rompe...', '3. Cinema o Divano?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Sacco a pelo o Letto?', '2. Verba volant...', '3. Visa o Mastercard?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Freddo o Caldo?', '2. Una mano lava...', '3. Bolt o Mayweather?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Mattina o Notte?', '2. Ambasciator non porta...', '3. Rap o Trap?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Penna blu o nera?', '2. Oltre il danno...', '3. PC fisso o Laptop?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Alcool o Analcolico?', '2. Piove governo...', '3. Ferrari o Lamborghini?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Barba o Baffi?', '2. Carta canta...', '3. Roma o Milano?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Mare o Lago?', '2. Squadra che vince...', '3. Londra o Parigi?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Bici o Piedi?', '2. Natale con i tuoi...', '3. New York o Tokyo?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Foto o Selfie?', '2. Chi è causa del suo mal...', '3. Cane o Lupo?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Crema o Cioccolato?', '2. Il troppo stroppia...', '3. Rolex o Casio?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Sole o Pioggia?', '2. Meglio un uovo oggi...', '3. Batman o Joker?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Tramonto o Alba?', '2. Chi non muore...', '3. Call of Duty o FIFA?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Carne o Verdura?', '2. L’unione fa la...', '3. Batman o Spiderman?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Sci o Snowboard?', '2. Occhio per occhio...', '3. Vans o Converse?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Tè freddo o caldo?', '2. Tra i due litiganti...', '3. Fortnite o Roblox?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Croccante o Morbido?', '2. San Martino ogni mosto...', '3. Ikea o Maison du Monde?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Calzini bianchi o neri?', '2. A buon intenditore...', '3. Star Wars o Star Trek?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Orologio o Bracciale?', '2. Dagli amici mi guardi...', '3. WhatsApp o Viber?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Specchio o Foto?', '2. Non c’è due senza...', '3. Burger o Salad?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Mare o Fiume?', '2. Finché c’è vita...', '3. Facebook o LinkedIn?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Tappo a vite o sughero?', '2. La fortuna aiuta gli...', '3. Nesquik o Kinder?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Grassa o Magra?', '2. In bocca al...', '3. Smart o SUV?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Riccio o Liscio?', '2. Gallina che canta...', '3. Prime Video o Sky?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Sushi o Sashimi?', '2. Per un punto Martin...', '3. H&M o Zara?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Jeans o Tuta?', '2. Se son rose...', '3. Ray-Ban o Oakley?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. E-book o Carta?', '2. Non dire quattro se...', '3. Canon o Nikon?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Mare o Grotta?', '2. Batti il ferro finché...', '3. Gucci o Prada?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Frutta o Dessert?', '2. Chi disprezza...', '3. Fiat o Alfa?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Nuoto o Corsa?', '2. Impara l’arte...', '3. Nutella o Nocciolata?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Tè verde o nero?', '2. Goccia dopo goccia...', '3. Nespresso o Moka?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pizza tonda o al taglio?', '2. Tutto il mondo è...', '3. Uber Eats o Deliveroo?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Bagno o Doccia?', '2. Chi tace...', '3. Revolut o N26?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Inverno o Autunno?', '2. Ogni scarrafone è...', '3. Lego o Playmobil?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Sci o Ciaspole?', '2. L’apparenza...', '3. Vespa o Lambretta?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Vino bianco o rosso?', '2. Il gioco non vale la...', '3. GNV o Moby?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Birra chiara o scura?', '2. A mali estremi...', '3. Estée Lauder o L’Oréal?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pantaloni o Shorts?', '2. Sotto la neve...', '3. Tezenis o Calzedonia?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Felpa con o senza zip?', '2. Chi pecora si fa...', '3. Coop o Conad?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Cappotto o Piumino?', '2. La curiosità uccise il...', '3. MediaWorld o Unieuro?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Camicia o Polo?', '2. Prevenire è meglio che...', '3. Esselunga o Lidl?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Jeans blu o neri?', '2. L’eccezione conferma la...', '3. Ryanair o EasyJet?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Sneakers bianche o nere?', '2. Avere le mani in...', '3. Trenitalia o Italo?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Mare calmo o mosso?', '2. Fare di tutta l’erba un...', '3. MSC o Costa?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Alba o Tramonto?', '2. Gettare la spugna...', '3. Sephora o Douglas?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Tè o Infuso?', '2. Mettere i puntini sulle...', '3. Decathlon o Cisalfa?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pasta al forno o lasagna?', '2. Prendere due piccioni con...', '3. OVS o H&M?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Yogurt o Budino?', '2. Rimanere a bocca...', '3. Carrefour o Pam?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Gelato in cono o coppetta?', '2. Cadere dalle...', '3. Euronics o Trony?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pizza margherita o farcita?', '2. Mettere il carro davanti ai...', '3. Vodafone o Tim?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Caffè macchiato o espresso?', '2. Salvare capra e...', '3. WindTre o Iliad?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Cornetto o Brioche?', '2. Rompere il...', '3. Sky o DAZN?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pane burro e marmellata o cioccolato?', '2. Alzare il...', '3. Rai o Mediaset?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Spremitura o Succo?', '2. Voltare la...', '3. Corriere o Repubblica?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Toast o Tramezzino?', '2. Chiudere un...', '3. Spotify o Tidal?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Piadina o Cassone?', '2. Essere al settimo...', '3. Nintendo o Sega?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Arancino o Supplì?', '2. Avere la coda di...', '3. Instagram o Pinterest?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pandoro o Panettone?', '2. Gettare fango...', '3. Google Maps o Waze?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Carnevale o Halloween?', '2. Arrampicarsi sugli...', '3. Zoom o Teams?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pasqua o Natale?', '2. Fare orecchie da...', '3. Dropbox o WeTransfer?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Ferragosto o Capodanno?', '2. Mangiare la...', '3. Uber o Cabify?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Compleanno o Onomastico?', '2. Gettare acqua sul...', '3. Shein o Temu?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Onomastico o Santo Stefano?', '2. Calare le...', '3. Glovo o Just Eat?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Venerdì 13 o 17?', '2. Tagliare la testa al...', '3. AliExpress o Wish?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Sciroppo o Pastiglia?', '2. Gallina che non becca...', '3. Zalando o ASOS?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Penna a sfera o stilografica?', '2. Rosso di mattina...', '3. Bolt o Jacobs?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Mare mosso o piatto?', '2. A ogni uccello il suo nido è...', '3. Twitter o X?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Scalzo o con i calzini?', '2. Chi ha tempo non aspetti...', '3. San Siro o Olimpico?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Torta di mele o cioccolato?', '2. L’ospite è come il pesce...', '3. Barbie o Oppenheimer?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Camminare o Correre?', '2. Non svegliare il can che...', '3. LinkedIn o BeReal?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Gomma o Matita?', '2. Tra moglie e marito...', '3. Marvel o Star Wars?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Felpa col cappuccio o senza?', '2. Chi troppo vuole...', '3. Parigi o Londra?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Amaro o Dolce?', '2. Cuor contento il ciel lo...', '3. Berlin o Tokyo?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Zaino in spalla o a mano?', '2. Una mano lava l’altra e...', '3. Sinner o Alcaraz?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Finestra aperta o chiusa?', '2. Meglio aver paura che...', '3. Mulino Bianco o Pavesi?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pizza sottile o spessa?', '2. Impara l’arte e...', '3. Harry Potter o Il Signore degli Anelli?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Occhiali da vista o da sole?', '2. Chi pecora si fa il lupo la...', '3. Duolingo o Babbel?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Foto a colori o bianco e nero?', '2. Morto un papa se ne fa...', '3. Shrek o Toy Story?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Dormire col cuscino o senza?', '2. Can che abbaia non...', '3. Subito o Wallapop?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Acqua naturale o frizzante?', '2. O mangi questa minestra o...', '3. Ken o Ryu?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. T-shirt bianca o nera?', '2. Chi ben comincia è a metà...', '3. Super Mario o Sonic?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Barba lunga o corta?', '2. La gatta frettolosa fece i micini...', '3. Spotify o YouTube Music?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Salsiccia o Wurstel?', '2. Piove, governo...', '3. Michael Jordan o LeBron James?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Tè freddo al limone o pesca?', '2. Batti il ferro finché è...', '3. Batman o Iron Man?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pasta in bianco o al pomodoro?', '2. A buon intenditore poche...', '3. Stradivarius o Pull&Bear?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Crostata o Plumcake?', '2. Il gioco non vale la...', '3. Tinder o Bumble?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Cuffie o Auricolari?', '2. Chi tace...', '3. Goku o Vegeta?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Portafoglio o Semplice tasca?', '2. Chi la dura la...', '3. Fortnite o Minecraft?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Cintura o Bretelle?', '2. Se son rose...', '3. Intimissimi o Tezenis?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Ascensore o Scale?', '2. Ogni scarrafone è bello a...', '3. Pandora o Swarovski?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Diario o Agenda sul telefono?', '2. Chi non risica non...', '3. Ryanair o ITA?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Sneakers alte o basse?', '2. Il tempo è...', '3. Burger King o Old Wild West?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Gelato alla frutta o creme?', '2. Meglio soli che mal...', '3. Lavazza o Illy?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Doccia calda o fredda?', '2. Tutto è bene quel che finisce...', '3. Sanremo o Eurovision?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Jeans larghi o stretti?', '2. Chi cerca...', '3. TikTok o Shorts?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Colazione dolce o salata?', '2. Patti chiari amicizia...', '3. Vecchio o Nuovo?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Libro cartaceo o E-reader?', '2. Verba volant scripta...', '3. Bolt o Jacobs?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Calcio o Basket?', '2. L’unione fa la...', '3. Google o DuckDuckGo?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Sushi o Sashimi?', '2. Meglio tardi che...', '3. Starbucks o Bar di fiducia?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Cappotto o Piumino?', '2. Chi la fa l’...', '3. Apple Watch o Casio?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Bagno o Doccia?', '2. Sbagliando s’...', '3. Disney o Pixar?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. T-shirt o Polo?', '2. Non c’è due senza...', '3. Coca Zero o Regular?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Moto o Scooter?', '2. Ride bene chi ride...', '3. PlayStation o Nintendo Switch?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Capelli ricci o lisci?', '2. L’abito non fa il...', '3. Zalando o Amazon?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Cane o Gatto?', '2. Non dire gatto se non ce l’hai nel...', '3. Messi o Ronaldo?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Treno o Aereo?', '2. Tanto va la gatta al lardo che...', '3. Telegram o WhatsApp?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Mare o Montagna?', '2. Rosso di sera bel tempo si...', '3. iOS o Android?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Dolce o Salato?', '2. Chi dorme non piglia...', '3. Nike o Adidas?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Penna o Matita?', '2. Meglio un uovo oggi che una gallina...', '3. Facebook o Instagram?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Tè o Caffè?', '2. L’erba del vicino è sempre più...', '3. Netflix o Prime Video?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Carne o Pesce?', '2. La pazienza è la virtù dei...', '3. Chrome o Safari?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Estate o Inverno?', '2. Chi trova un amico trova un...', '3. PC o Console?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Pizza o Hamburger?', '2. Mal comune mezzo...', '3. Spotify o Radio?'] },
    { tipo: 'flash', cat: 'Flash (Falle tutte e 3!)', domande: ['1. Mattina o Sera?', '2. Una ciliegia tira l’...', '3. BMW o Mercedes?'] },

    // --- CHI DEL GRUPPO ---
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si dimentichi dove ha parcheggiato?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più spendaccione quando esce?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi rimarrebbe bloccato fuori casa per aver perso le chiavi?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un meme virale?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più "fissato" con la pulizia?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si addormenti a una festa?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi mangerebbe l’ultima fetta di pizza senza chiedere?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che vinca un reality show?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più ritardatario cronico?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che mandi un messaggio alla persona sbagliata?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più coraggioso in una situazione di emergenza?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si perda seguendo il GPS?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più "social" del gruppo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che pianga guardando un cartone animato?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più permaloso se riceve una critica?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che venga arrestato per un malinteso?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il miglior cuoco tra tutti voi?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un eremita in montagna?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più informato sugli ultimi pettegolezzi?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che vinca un milione e lo finisca in un mese?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più ipocondriaco del gruppo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia una gaffe davanti a un superiore?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si offra per pagare il conto?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un collezionista di cose strane?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più testardo durante una discussione?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che vada a un appuntamento al buio?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più dormiglione del gruppo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che rompa il telefono appena comprato?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più "tech-savvy" (esperto di tecnologia)?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia bungee jumping?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più selettivo col cibo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che dimentichi il proprio compleanno?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che viva all’estero?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più sportivo tra voi?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si sposi per primo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che rimanga l’ultimo single?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più mattiniero del gruppo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che compri un’auto sportiva?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più parsimonioso (tirchio)?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che venga scambiato per una celebrità?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che pianga a un matrimonio?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più disordinato cronico?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un politico?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che sopravviva a un’apocalisse zombie?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia una maratona di serie TV di 24 ore?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più spericolato alla guida?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un guru della crescita personale?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più competitivo, anche nei giochi stupidi?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si perda dentro un aeroporto?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più goloso di dolci?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia uno scherzo telefonico?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che compri una casa infestata?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che vinca un premio Nobel?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più riflessivo del gruppo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che dimentichi il nome di qualcuno appena presentato?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più amante degli animali?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un detective?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia un discorso imbarazzante a un compleanno?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più calmo sotto pressione?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che mangi cibo per strada?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che rida nel momento meno opportuno?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un critico gastronomico?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più ordinato nel lavoro o nello studio?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia una pazzia per amore?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un atleta professionista?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più pessimista del gruppo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che compri vestiti uguali in colori diversi?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si faccia un selfie con uno sconosciuto?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che entri nel Guinness dei Primati?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia il primo passo in amore?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più amante della vita notturna?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un inventore?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che rimanga bloccato in un ascensore?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più sognatore ad occhi aperti?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che scriva un’autobiografia?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia paracadutismo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più attento alle tendenze di moda?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che dimentichi di caricare il telefono?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi uno chef stellato?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più abile nei lavori manuali?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si sposti a vivere su un’isola deserta?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia un provino per un film?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più riservato del gruppo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un famoso YouTuber?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che vinca a poker?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che inizi a ridere da solo ricordando qualcosa?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più puntiglioso sulla grammatica?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che compri un oggetto costosissimo e inutile?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia tardi perché non sa cosa mettersi?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un insegnante?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che rimanga senza benzina in autostrada?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più amante dei videogiochi?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che pianga per la felicità di qualcun altro?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che vinca una gara di mangiatori di pizza?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più abile a mentire nei giochi di società?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia un viaggio zaino in spalla?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più ansioso per i piccoli dettagli?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che adotti dieci gatti?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che parli nel sonno?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si faccia un tatuaggio abbinato con un amico?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un hacker?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia la fila per ore per l’ultimo iPhone?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più saggio a cui chiedere consiglio?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un comico?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si addormenti durante un film al cinema?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che trovi un tesoro sepolto?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un astronauta?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che vinca un concorso di bellezza?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più "notturno" del gruppo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si faccia influenzare da una pubblicità?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più bravo a cantare (anche se sotto la doccia)?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un miliardario?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia un viaggio last-minute?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un artista famoso?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che scriva una canzone?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un campione di scacchi?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si faccia bannare da un social?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che vinca un quiz televisivo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia yoga ogni mattina?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un subacqueo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia un errore di battitura in un messaggio serio?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un architetto?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si dimentichi il pranzo a casa?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia un record mondiale?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un pasticciere?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un filosofo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia una gita fuori porta ogni weekend?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un regista?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si compri un cane enorme?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un collezionista di vinili?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si faccia la propria birra in casa?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia un corso di ceramica?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un DJ?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si compri un drone?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un fotografo naturalista?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si faccia una maratona di Harry Potter ogni anno?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un esperto di vini?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si compri una moto d’epoca?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un sommelier?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che faccia un orto sul balcone?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un pilota di aerei?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si faccia un viaggio in mongolfiera?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un giardiniere esperto?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si compri un telescopio?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un esperto di storia?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si faccia un tatuaggio sulla schiena?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un surfista?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si compri una barca?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che diventi un archeologo?' },
    { tipo: 'chi', cat: 'Chi del gruppo?', testo: 'Chi è il più probabile che si faccia un viaggio in Antartide?' }
];

// --- VARIABILI DI STATO ---
let squadre = []; 
let indiceTurno = 0;
let mazzoCopiato = [...mazzo]; 
let cartaCorrente = null;

function aggiungiSquadra() {
    const input = document.getElementById('team-name-input');
    const nome = input.value.trim();
    if (!nome) return;
    squadre.push({ nome: nome, punti: 0 });
    input.value = "";
    document.getElementById('teams-list').innerHTML = squadre.map(s => `<li>• ${s.nome}</li>`).join('');
    if (squadre.length >= 2) document.getElementById('btn-start').classList.remove('hidden');
}

function iniziaGioco() {
    document.getElementById('setup-container').classList.add('hidden');
    document.getElementById('main-game').classList.remove('hidden');
    aggiornaUI_Turno();
}

function aggiornaUI_Turno() {
    document.getElementById('current-team-display').innerText = squadre[indiceTurno].nome;
    document.getElementById('leaderboard').innerText = squadre.map(s => s.nome.toUpperCase() + ": " + s.punti).join("  |  ");
}
function pescaCarta() {
    if (mazzoCopiato.length === 0) mazzoCopiato = [...mazzo];
    const index = Math.floor(Math.random() * mazzoCopiato.length);
    cartaCorrente = mazzoCopiato.splice(index, 1)[0];
    
    // Mostra i controlli e nasconde il tasto pesca
    document.getElementById('btn-pesca').classList.add('hidden');
    document.getElementById('controls').classList.remove('hidden');
    
    const cardElem = document.getElementById('card-display');
    const mainText = document.getElementById('main-text');
    const badge = document.getElementById('category-badge');
    
    // Forza il tipo per il colore del bordo
    const tipo = cartaCorrente.tipo.toLowerCase().trim();
    cardElem.className = 'card ' + tipo; 
    badge.innerText = cartaCorrente.cat;

    // --- LOGICA DI FORMATTAZIONE TESTO ---
    
    if (tipo === 'standard') {
        // SINCRONIA: Numeri 1, 2, 3... e ogni domanda va a capo
        mainText.innerHTML = cartaCorrente.domande
            .map(d => d.replace(/^\d+\.\s*/, '')) // Pulisce numeri vecchi
            .map((d, i) => `<div style="margin-bottom:15px;">${i + 1}. ${d}</div>`)
            .join("");

    } else if (tipo === 'flash') {
        // FLASH: Niente numeri, solo le parole una sotto l'altra, belle grandi
        const items = Array.isArray(cartaCorrente.domande) ? cartaCorrente.domande : [cartaCorrente.testo];
        mainText.innerHTML = items
            .map(item => `<div style="margin-bottom:10px; font-weight:900; text-transform:uppercase;">${item}</div>`)
            .join("");

    } else {
        // CHI DEL GRUPPO: Testo semplice pulito
        mainText.innerHTML = `<div style="font-style:italic;">"${cartaCorrente.testo}"</div>`;
    }
}

function gestisciRisposta(vinto) {
    if (vinto) {
        squadre[indiceTurno].punti++;
        aggiornaUI_Turno();
        pescaCarta();
    } else {
        document.getElementById('main-text').innerHTML = "<span style='color:var(--color-fail)'>TURNO FINITO</span>";
        document.getElementById('controls').classList.add('hidden');
        setTimeout(() => {
            indiceTurno = (indiceTurno + 1) % squadre.length;
            document.getElementById('btn-pesca').classList.remove('hidden');
            document.getElementById('card-display').className = 'card';
            document.getElementById('main-text').innerText = "Tocca a " + squadre[indiceTurno].nome;
            document.getElementById('category-badge').innerText = "Cambio Turno";
            aggiornaUI_Turno();
        }, 1500);
    }
}